#include"IO.h"
/* 冒泡排序 */
// 主函数
IIO IIII IO OI IOOO
// 初始化数组
IIO OIIOI IOO OOI OOO IOOO I OIO I OIO I OIO I OIO I OIO I OIO I OIO I OIO I OO 
I OIO I OIO I OIO I OIO I OIO I OIO I OIO I OO  
I OIO I OIO I OIO I OIO I OIO I OIO I OO 
I OIO I OIO I OIO I OIO I OIO I OO 
I OIO I OIO I OIO I OIO I OO  
I OIO I OIO I OIO I OO  
I OIO I OIO I OO 
I OIO I OO  
I OO   
O  
OOOI II
IIO OIIOII OO OIIOIIO OO OIIOIIOO II 

OIII IO  OIIOOIIOIO OIIOOIIOIO OIIIOOI OIIOOIIO OI II
OIII IO OIIIOO OI II

// 排序前进行遍历
IOOII IO OIIOII OOO O II OIIOII OIOIO I OIO I OIO I OIO I OIO I OIO I OIO I OIO I OIO I OIO I II OIIOII OIOO OI IOOO 

OIII IO OIIIO OO OIIOI IOO OIIOII OOI OI II   

OOOI
OIII IO OIIOOIIO OI II

// 冒泡排序主体
IOOII IO OIIOII OOO O II OIIOII OIOIO I OIO I OIO I OIO I OIO I OIO I OIO I OIO I OIO I II OIIOII OIOO OI IOOO

IOOII IO OIIOIIO OOO I II OIIOIIO OIOIO I OIO I OIO I OIO I OIO I OIO I OIO I OIO I OIO I OIO I IOI OIIOII II OIIOIIO OIOO OI IOOO

IOIOII IO  OIIOI IOO OIIOIIO  OOI OIOIO OIIOI IOO OIIOIIO IOI I OOI OI IOOO
OIIOIIOO OOO OIIOI IOO OIIOIIO  OOI II
OIIOI IOO OIIOIIO  OOI OOO OIIOI IOO OIIOIIO IOI I OOI II
OIIOI IOO OIIOIIO IOI I OOI OOO OIIOIIOO II

OOOI

OOOI

OOOI

OIII IO OIIIOOO OI II

// 排序后遍历输出数组
IOOII IO OIIOII OOO O II OIIOII OIOIO I OIO I OIO I OIO I OIO I OIO I OIO I OIO I OIO I OIO I II OIIOII OIOO OI IOOO 

OIII IO OIIIO OO OIIOI IOO OIIOII OOI OI II  

OOOI

OIII IO OIIOOIIO OI II

IOIO O II 
OOOI
