#include"IO.h"
/* 快速排序 */


// 快速排序选择部分
IIO OIIOOIII IO  IIO OIIOIOI OO IIO OIIOIII OO IIO IOIIO OIIOI OI IOOO
IIO OIIOIIOIOI  OOO  OIIOI IOO  OIIOIOI OOI II  
IIO OIIOIOO  OOO  OIIOIOI OO OIIOIIOI  OOO  OIIOIII II
IOOI IO OIIOIOO  OIOIO  OIIOIIOI OI  IOOO
IOOI IO OIIOIOO  OIOIO  OIIOIIOI  IOIOOI  OIIOI IOO OIIOIIOI OOI  IOIOI OIIOIIOIOI OI  OIIOIIOI IOII II
OIIOI IOO OIIOIOO OOI  OOO  OIIOI IOO OIIOIIOI OOI II
IOOI IO OIIOIOO  OIOIO  OIIOIIOI  IOIOOI  OIIOI IOO OIIOIOO OOI  OIOIO  OIIOIIOIOI OI  OIIOIOO OIOO II
OIIOI IOO OIIOIIOI OOI  OOO  OIIOI IOO OIIOIOO OOI II
OOOI
OIIOI IOO OIIOIOO OOI  OOO  OIIOIIOIOI II
IOIO OIIOIOO II
OOOI

// 快速排序二分部分
IOIOOIO OIIOOIIOI IO IIO OIIOIOI OO IIO OIIOIII OO IIO IOIIO OIIOI OI IOOO
IOIOII IO OIIOIOI OIOIO  OIIOIII OI IOOO
IIO OIIOIIOIOII OOO  OIIOOIII IO OIIOIOI OO OIIOIII OO OIIOI OI II
OIIOOIIOI IO OIIOIOI OO OIIOIIOIOII OO OIIOI OI II
OIIOOIIOI IO OIIOIIOIOII OIO I OO OIIOIII OO OIIOI OI II
OOOI
 OOOI

// 进行遍历输出数组的函数
IIO OIIOOIIOII IO IIO OIIOIIOIO OO IIO IOIIO OIIOI OI IOOO
// OIII IO  OIIIOO OI  II
IOOII IO IIO OIIOII  OOO  O II OIIOII  OIOIO  OIIOIIOIO II OIIOII OIOO OI IOOO
OIII IO OIIIO OO OIIOI IOO  OIIOII OOI OI II
OOOI
OIII IO  OIIOOIIO OI II
OOOI

// 主函数
IIO IIII IO  OI  IOOO
// 初始化数组
IIO OIIOI IOO OOI OOO IOOO I OIO I OIO I OIO I OIO I OIO I OIO I OIO I OIO I OO 
I OIO I OIO I OIO I OIO I OIO I OIO I OIO I OO  
I OIO I OIO I OIO I OIO I OIO I OIO I OO 
I OIO I OIO I OIO I OIO I OIO I OO 
I OIO I OIO I OIO I OIO I OO  
I OIO I OIO I OIO I OO  
I OIO I OIO I OO  
I OIO I OO  
I OO  
O  
OOOI II 
IIO OIIOIIOIO  OOO  OIIOIIOIOO IO OIIOI OI  IOIIII OIIOIIOIOO IO OIIOI IOO  O OOI OI II

OIII IO  OIIOOIIOIO OIIOOIIOIO OIIIOOIO OIIOOIIO OI II
OIII IO  OIIIOO OI  II  

// 排序前进行遍历输出数组
OIIOOIIOII IO OIIOIIOIO OO OIIOI OI  II

// 对数组进行快速排序
OIIOOIIOI IO O OO OIIOIIOIO OO OIIOI OI  II
OIII IO  OIIIOOO OI  II 

// 排序后进行遍历输出数组
OIIOOIIOII IO OIIOIIOIO OO OIIOI OI  II
IOIO O II
OOOI